# .streamlit/config.toml
# Streamlit configuration for deployment

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
# Vermont Green Mountains theme
# Colors inspired by Vermont's forests, mountains, and autumn foliage
primaryColor = "#2D5F3F"        # Deep forest green (Vermont's evergreen forests)
backgroundColor = "#F5F3EE"      # Soft cream (morning mist over mountains)
secondaryBackgroundColor = "#E8E5DC"  # Light sage (mountain meadows)
textColor = "#1A3329"            # Dark pine (deep forest)
font = "sans serif"
